#!/bin/zsh
# Author: Michael Ciociola
# License: GPLv3

bspc config border_width            0
bspc config window_gap              37

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config presel_feedback_color   \#aaaaaa

bspc config focus_follows_pointer   true
bspc config single_monocle          false

bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config pointer_action2         none
bspc config pointer_action3         resize_corner

bspc rule -a Firefox                desktop=^2
bspc rule -a Chromium               desktop=^2
bspc rule -a Signal                 desktop=^3
bspc rule -a discord                desktop=^3
bspc rule -a ncmpcpp                desktop=^5
bspc rule -a Pavucontrol            desktop=^5
bspc rule -a QjackCtl               desktop=^5
bspc rule -a emacs                  desktop=^4
bspc rule -a mpv                    desktop=^7
bspc rule -a play                   desktop=^7
bspc rule -a kitty                  rectangle=800x600+0+0 center=true

bspc rule -a Carla                  state=tiled
bspc rule -a carla-bridge-win32.exe state=floating
bspc rule -a carla-bridge-win64.exe state=floating
bspc rule -a "Tor Browser"          state=floating
bspc rule -a Screenkey              manage=off

xsetroot -cursor_name left_ptr

bspwm-fullscreen &
eww daemon &

if [[ "$HOST" == 'iroh' ]]; then
  # bspc monitor DP-4 -d 1 2 3 4 5 6 7
  # bspc monitor HDMI-0 -d 8 9 10
  bspc monitor DP-4 -d 1 2 3 4 5 6 7 8 9
fi

if [[ "$HOST" = 'hatsune' ]]; then
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
fi

