#! /bin/sh
# Author: Michael Ciociola
# License: GPLv3


bspc monitor DP-4 -d web term chat code music read 7
bspc monitor eDP-1 -d web term chat code music read 7
bspc monitor HDMI-1 -d 8 9 10

bspc config border_width            0
bspc config window_gap              37

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config presel_feedback_color   \#aaaaaa

bspc desktop ^1 -l monocle

bspc config super                   mod4
bspc config click_to_focus          true
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false
bspc config single_monocle          true

bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config pointer_action2         none
bspc config pointer_action3         resize_corner

bspc rule -a Firefox                desktop=^1
bspc rule -a Signal                 desktop=^3
bspc rule -a Discord                desktop=^3
bspc rule -a Spotify                desktop=^5
bspc rule -a ncmpcpp                desktop=^5
bspc rule -a Pavucontrol            desktop=^5
bspc rule -a Emacs                  state=tiled
bspc rule -a QjackCtl               state=floating
# bspc rule -a Thunar                 state=floating
bspc rule -a mpv                    state=floating
# bspc rule -a Gimp                   desktop=^8 state=floating follow=on

bspc rule -a Carla                  state=tiled desktop=^5
bspc rule -a carla-bridge-win32.exe state=floating desktop=^5
bspc rule -a carla-bridge-win64.exe state=floating desktop=^5
bspc rule -a "Tor Browser"          state=floating desktop=^1
bspc rule -a Screenkey              manage=off

xsetroot -cursor_name left_ptr
